### ISSUE TITLE
請調整相關事項

### ISSUE THREAD

**Issue by hatelove** [larrynung/TDDDay2HomeWork#1]
1. TDD的過程，要享受到TDD的好處，請試著先寫一個測試案例，再調整 production code 以通過它。在這個過程中，會因為要讓 test code 能編譯通過，而直接從測試案例中產生 production code 的骨架出來。而這就是享受到 TDD 能讓 API 好用、好讀的好處。因為命名會跟著需求和 domain model 走，可用性上也會先從使用端來考量。而且會讓 API 設計地更加抽象。
2. 不在需求裡面的部分，不加入測試案例中，容易造成混淆。
3. 測試程式不含邏輯，要越像直述句，越不需要去維護到他，需求異動時能越 robustness 越好。否則測試程式的維護成本會急速上升。

建議重新調整一次專案，試著從上面的建議在練習一次，一定會有不同的感覺

**Comment by larrynung** [comment]
已嚐試修正 2、3 ，請過目...

**Comment by hatelove** [comment]
2 跟 3 調整地很OK，1的部分可以在別的例子再練習、感受一下就好。

commit review comment裡面，我有提到一個是 API 易讀跟呼叫端易用性的部分，不一定對，但對用來的人來說，那樣子腦袋會簡單一些。想買什麼書，就一直加進去車子裡。Dictionary 會帶著到底有什麼東西（key）不能重複，或是我之後存取會直接拿 key 來存取，以達到 O(1) 的效率，所以用 Dictionary 來做。
